### ISSUE TITLE
Split out functions to call them separately

### ISSUE THREAD

**Issue by craigmdennis** [craigmdennis/sass-height#1]
Calculating font size, line-heights and padding should be split into separate functions that are aware of the context in which they are being called.

Inspired by susy, it would be great to do:

``` scss
.myclass {
  @include height(16px, 32px);
  padding-left: pad(16px, 32px); // Return the vertical padding units
  padding-right: pad(16px, 32px);
}
```

``` scss
.mytext {
  font-size: fs(16px); // Converts to rems
  line-height: lh(16px); // Returns a unitless value based on next baseline
}
```
