### ISSUE TITLE
Add the ability to override the default baseline on case-by-case basis

### ISSUE THREAD

**Issue by craigmdennis** [craigmdennis/sass-height#9]
Currently you can only do this by:

``` scss
// Override the default baseline for larger line-height
$sassheight: ( baseline: 8px ) !default;
.section__intro {
  @include height( $section__intro__size );
}
$sassheight: ( baseline: 4px );
```

Something like `@include height( 24px, auto, 8px );` could work (where `auto` doesn't set a height using padding).
